"""Stocks API routes — broker-trade ingestion + session-review access.

The local arnold app POSTs every closed round-trip here (entry/exit/PnL/signal
context). Without this, trade outcomes only existed in stdout + a 100-deep
in-memory dashboard deque, lost on container restart.

Session reviews are generated by backend/scripts/session_review.py (cron at
23:55 UTC) and archived to /app/data/rl/sessions/<YYYY-MM-DD>.json. The
endpoints here let the local frontend (and humans via curl) read them back.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from ...db.models import BrokerTrade, StockSignal
from ..deps import get_db

log = logging.getLogger(__name__)

router = APIRouter(prefix="/api/stocks", tags=["stocks"])

_SESSIONS_DIR = Path("/app/data/rl/sessions")
_TRADING_PAUSED_FLAG = Path("/app/data/rl/trading_paused")


@router.get("/runtime-diagnostic")
def runtime_diagnostic(request: Request):
    """Drill-down state for debugging why signals aren't firing trades.

    Shows: is LevelMonitor wired to the broker? How many levels/zones does
    it know about? Are tick callbacks attached? Is orderflow fresh enough
    to produce a non-zero of_score?
    """
    app = request.app
    rt = getattr(app.state, "stocks_runtime", None)
    lm = getattr(app.state, "level_monitor", None)
    tb = getattr(app.state, "stocks_tick_buffer", None)

    diag = {
        "runtime_present": rt is not None,
        "level_monitor_present": lm is not None,
        "broker_adapter_on_level_monitor": None,
        "broker_adapter_same_as_runtime": None,
        "level_count": 0,
        "zone_count": 0,
        "signal_callback_count": 0,
        "tick_buffer_size": 0,
    }
    if lm is not None:
        lm_adapter = getattr(lm, "_broker_adapter", None)
        diag["broker_adapter_on_level_monitor"] = lm_adapter is not None
        if rt is not None:
            diag["broker_adapter_same_as_runtime"] = lm_adapter is rt.adapter
        diag["level_count"] = len(getattr(lm, "_levels", []))
        diag["zone_count"] = len(getattr(lm, "_zones", []))
        diag["signal_callback_count"] = len(getattr(lm, "_signal_callbacks", set()))
        # Breakdown of raw_levels by `type` so the TV overlay debug can
        # confirm TPO/swing/FVG/etc levels are actually being broadcast.
        try:
            from collections import Counter

            raw = lm.get_raw_levels() if hasattr(lm, "get_raw_levels") else []
            diag["raw_level_count"] = len(raw)
            diag["raw_level_types"] = dict(Counter(lv.get("type") or "unknown" for lv in raw))
            # Also dump _levels names — these are the actual zone-clustering
            # inputs (raw_levels + session-dict extracted: poc/tpo*/ib*/vwap*).
            mlevels = getattr(lm, "_levels", []) or []
            diag["_levels_names"] = dict(Counter(getattr(lv, "name", "?") for lv in mlevels))
        except Exception as exc:
            diag["raw_level_types_error"] = str(exc)
    if tb is not None:
        try:
            diag["tick_buffer_size"] = len(tb.ticks)
        except Exception:
            diag["tick_buffer_size"] = -1
    if rt is not None:
        diag["account_id"] = rt.client._account_id
        diag["stream_running"] = getattr(rt.stream, "_running", None)
        diag["zone_seed_task_done"] = rt.tasks.get("zone_seed").done() if rt.tasks.get("zone_seed") else None
    try:
        from ...stocks import dashboard as _dashboard

        diag["dashboard_zone_count"] = len(_dashboard._state.get("zones") or [])
    except Exception as exc:
        diag["dashboard_zone_count_error"] = str(exc)
    return diag


@router.get("/runtime-status")
def runtime_status(request: Request):
    """Is the autonomous server-side broker alive, what's the current
    position, and is the trading_paused kill switch active?
    """
    rt = getattr(request.app.state, "stocks_runtime", None)
    paused = _TRADING_PAUSED_FLAG.exists()

    if rt is None:
        return {
            "running": False,
            "paused": paused,
            "reason": "STOCKS_AUTONOMOUS not set or bootstrap failed at startup",
        }

    adapter = rt.adapter
    tracker = adapter.tracker
    # The TV overlay shape needs entry/stop/tp on the chart's Y axis. The
    # tracker carries entry_price + stop_price (sometimes 0.0 right after
    # a fill before the GatewayUserAccount payload lands), but tp_price
    # only lives on the adapter's `_pending_trade` dict. Expose all three
    # with safe fallbacks so the userscript always has on-chart anchors.
    pending = getattr(adapter, "_pending_trade", None) or {}
    entry = tracker.entry_price or float(pending.get("entry_price") or 0.0) or float(pending.get("signal_price") or 0.0)
    stop = tracker.stop_price or pending.get("stop_price")
    tp = pending.get("tp_price")
    return {
        "running": True,
        "paused": paused,
        "halted": adapter._halted,
        "halt_reason": adapter._halt_reason,
        "account_id": rt.client._account_id,
        "position": {
            "flat": tracker.is_flat,
            "side": tracker.side,
            "size": tracker.size,
            "entry_price": entry,
            "stop_price": float(stop) if stop is not None else 0.0,
            "tp_price": float(tp) if tp is not None else None,
            "peak_R": tracker.peak_R,
            "locked_half_R": tracker.locked_half_R,
        },
        "session": {
            "pnl": tracker.session_pnl,
            "trade_count": tracker.trade_count,
            "consecutive_stops": tracker.consecutive_stops,
            "trailing_dd": tracker.trailing_dd,
        },
    }


@router.get("/account")
async def get_account(request: Request):
    """Active TopstepX account + risk limits, scoped per prop firm and per
    sports profile.

    Shape is intentionally an array of prop_firms each with an array of
    accounts so adding a second prop firm or surfacing a second active
    account is purely additive.

    Per-profile filtering: if the active sports profile has a
    `topstepx_account_id` set, only that account is returned (so two
    profiles each running their own broker don't leak each other's
    balances). When unset, returns every account from TopstepX so the
    user can see what's there and bind one.
    """
    rt = getattr(request.app.state, "stocks_runtime", None)
    if rt is None:
        return {"prop_firms": []}

    client = rt.client
    cfg = client._config

    cache = getattr(request.app.state, "_account_cache", None)
    try:
        data = await client._post(
            "/api/Account/search",
            {"onlyActiveAccounts": True},
        )
        accounts = data.get("accounts", []) if isinstance(data, dict) else []
    except Exception:
        log.exception("TopstepX /Account/search failed")
        if cache is not None:
            return cache
        return {"prop_firms": []}

    # Resolve which TopstepX account the active sports profile owns. If
    # bound, hide the others — keeps profile isolation intact.
    from ...db.models import Profile, get_session

    profile_account_id: int | None = None
    active_profile_id: int | None = None
    db = get_session()
    try:
        active_profile = db.query(Profile).filter(Profile.is_active).first()
        if active_profile is not None:
            active_profile_id = active_profile.id
            profile_account_id = active_profile.topstepx_account_id
    finally:
        db.close()

    active_id = client._account_id
    out_accounts = []
    for a in accounts:
        # Skip accounts not owned by the active profile, when bound.
        if profile_account_id is not None and a.get("id") != profile_account_id:
            continue
        is_active = a.get("id") == active_id
        out_accounts.append(
            {
                "id": a.get("id"),
                "name": a.get("name", ""),
                "product": (a.get("name", "").split("-", 1)[0] or "").upper(),
                "balance": a.get("balance"),
                "can_trade": a.get("canTrade", False),
                "simulated": a.get("simulated", False),
                "active": is_active,
                "limits": {
                    "max_trailing_dd": cfg.max_trailing_dd,
                    "max_daily_loss": cfg.max_daily_loss,
                }
                if is_active
                else None,
            }
        )

    payload = {
        "prop_firms": [{"id": "topstepx", "name": "TopstepX", "accounts": out_accounts}],
        "active_profile_id": active_profile_id,
        "profile_bound_account_id": profile_account_id,
    }
    request.app.state._account_cache = payload
    return payload


@router.post("/account/bind")
def bind_account_to_profile(payload: dict, db: Session = Depends(get_db)):
    """Bind a TopstepX account_id to the active sports profile.

    Future-compat for multi-profile trading: each profile may own one
    TopstepX account. Pass {"account_id": <int|null>} — null clears the
    binding. Caller must already have an active profile.
    """
    from ...db.models import Profile

    account_id = payload.get("account_id")
    if account_id is not None:
        try:
            account_id = int(account_id)
        except (TypeError, ValueError):
            raise HTTPException(status_code=400, detail="account_id must be an integer or null") from None

    active = db.query(Profile).filter(Profile.is_active).first()
    if active is None:
        raise HTTPException(status_code=409, detail="no active profile") from None

    active.topstepx_account_id = account_id
    db.commit()
    db.refresh(active)
    return {
        "profile_id": active.id,
        "profile_name": active.name,
        "topstepx_account_id": active.topstepx_account_id,
    }


@router.post("/halt")
async def halt_trading(request: Request, flatten: bool = True):
    """Emergency stop: writes the /app/data/rl/trading_paused flag AND
    optionally liquidates any open position.

    The paused flag raises the signal-confidence floor to 0.99, muting
    every future signal until the flag is removed.
    """
    try:
        _TRADING_PAUSED_FLAG.parent.mkdir(parents=True, exist_ok=True)
        _TRADING_PAUSED_FLAG.touch()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"could not set pause flag: {e}") from None

    flattened = False
    flatten_err = None
    rt = getattr(request.app.state, "stocks_runtime", None)
    if flatten and rt is not None and not rt.adapter.tracker.is_flat:
        try:
            await rt.adapter.flatten("manual_halt")
            flattened = True
        except Exception as e:
            flatten_err = str(e)

    return {
        "paused": True,
        "flattened": flattened,
        "flatten_error": flatten_err,
        "note": "remove /app/data/rl/trading_paused to resume",
    }


@router.post("/resume")
def resume_trading():
    """Remove the trading_paused flag so new signals fire again."""
    if _TRADING_PAUSED_FLAG.exists():
        _TRADING_PAUSED_FLAG.unlink()
        return {"paused": False, "removed": True}
    return {"paused": False, "removed": False, "note": "flag was not set"}


@router.post("/recover")
async def recover_trading(request: Request):
    """Self-heal a stuck-tracker halt without a container restart.

    When the reconcile loop fires `size_mismatch` because the local tracker
    believes a position is open that the broker has already closed, the
    `flatten()` path now (a) writes the missed broker_trades row from
    Trade/search history, and (b) clears the tracker. This endpoint runs
    that flow on demand and additionally clears `_halted` so trading can
    resume in the same container.
    """
    rt = getattr(request.app.state, "stocks_runtime", None)
    if rt is None:
        raise HTTPException(status_code=503, detail="stocks runtime not initialized")
    adapter = rt.adapter
    flatten_result = await adapter.flatten("manual_recover")
    cleared_halt = False
    if adapter._halted:
        adapter._halted = False
        adapter._halt_reason = ""
        cleared_halt = True
    return {
        "halt_cleared": cleared_halt,
        "tracker_flat": adapter.tracker.is_flat,
        "halted": adapter._halted,
        "halt_reason": adapter._halt_reason,
        "flatten_result": flatten_result,
    }


def _parse_ts(v: str | float | None) -> datetime | None:
    if v is None:
        return None
    if isinstance(v, (int, float)):
        return datetime.fromtimestamp(v, tz=timezone.utc).replace(tzinfo=None)
    try:
        return datetime.fromisoformat(str(v).replace("Z", "+00:00")).astimezone(timezone.utc).replace(tzinfo=None)
    except Exception:
        return None


class BrokerTradeIn(BaseModel):
    """Round-trip trade payload from the local broker_adapter."""

    ts: str | float | None = None
    session_date: str
    symbol: str = "NQ"
    side: str
    size: int
    entry_price: float
    stop_price: float | None = None
    exit_price: float | None = None
    tp_price: float | None = None
    pnl_dollars: float | None = None
    pnl_r: float | None = None
    fill_latency_ms: float | None = None
    slippage_ticks: float | None = None
    was_stop: bool | None = None
    trail_count: int | None = None
    stop_ticks: float | None = None
    signal_action: str | None = None
    signal_confidence: float | None = None
    signal_zone: float | None = None
    signal_trigger: str | None = None
    signal_cont_p: float | None = None
    signal_rev_p: float | None = None
    orderflow_score: float | None = None
    closed_at: str | float | None = None
    # Idempotency: a deterministic key the client can supply so retries don't
    # double-insert. We store it in signal_trigger for now (string column,
    # already indexed-friendly via session_date+ts).
    client_dedupe_key: str | None = Field(default=None)


@router.post("/broker-trades")
def ingest_broker_trade(body: BrokerTradeIn, db: Session = Depends(get_db)):
    """Persist a closed round-trip from the local TopstepX adapter.

    Idempotent on (closed_at, symbol, side, entry_price, size) — the
    client should send the same payload on retry; we'll skip if it already
    exists.
    """
    closed_at = _parse_ts(body.closed_at)
    ts = _parse_ts(body.ts) or datetime.utcnow()

    # Cheap dedupe: same closed_at + entry_price + size + side already in DB.
    if closed_at is not None:
        existing = (
            db.query(BrokerTrade.id)
            .filter(
                BrokerTrade.closed_at == closed_at,
                BrokerTrade.symbol == body.symbol,
                BrokerTrade.side == body.side,
                BrokerTrade.entry_price == body.entry_price,
                BrokerTrade.size == body.size,
            )
            .first()
        )
        if existing:
            return {"id": existing[0], "deduped": True}

    row = BrokerTrade(
        ts=ts,
        session_date=body.session_date,
        symbol=body.symbol,
        side=body.side,
        size=body.size,
        entry_price=body.entry_price,
        stop_price=body.stop_price,
        tp_price=body.tp_price,
        exit_price=body.exit_price,
        stop_ticks=body.stop_ticks,
        was_stop=body.was_stop,
        trail_count=body.trail_count,
        pnl_dollars=body.pnl_dollars,
        pnl_r=body.pnl_r,
        fill_latency_ms=body.fill_latency_ms,
        slippage_ticks=body.slippage_ticks,
        signal_action=body.signal_action,
        signal_confidence=body.signal_confidence,
        signal_zone=body.signal_zone,
        signal_trigger=body.signal_trigger,
        signal_cont_p=body.signal_cont_p,
        signal_rev_p=body.signal_rev_p,
        orderflow_score=getattr(body, "orderflow_score", None),
        closed_at=closed_at,
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    return {"id": row.id, "deduped": False}


@router.get("/broker-trades")
def list_broker_trades(
    days: int = 30,
    symbol: str | None = None,
    db: Session = Depends(get_db),
):
    """Return recent persisted trades scoped to the active profile.

    Trading equity / R / win-rate must not bleed across profiles when one
    user has multiple TopstepX accounts (e.g. eval + funded). Filters by
    profile_id when an active profile exists; legacy NULL rows pre-binding
    are returned only if no profile is active so we don't silently hide
    historical trades during the migration window.
    """
    from ...db.models import Profile
    from ..deps import get_db as _  # noqa: F401  (keeps imports local-scoped)

    active = db.query(Profile).filter(Profile.is_active).first()

    cutoff = datetime.utcnow() - __import__("datetime").timedelta(days=days)
    q = db.query(BrokerTrade).filter(BrokerTrade.ts >= cutoff)
    if active is not None:
        # Show trades the active profile owns. Fall back to NULL rows only
        # when this profile has no claimed TopstepX account — otherwise the
        # active profile sees its scoped trades and unbound trades stay
        # invisible until backfilled.
        if active.topstepx_account_id is not None:
            q = q.filter(BrokerTrade.profile_id == active.id)
        else:
            from sqlalchemy import or_

            q = q.filter(or_(BrokerTrade.profile_id == active.id, BrokerTrade.profile_id.is_(None)))
    if symbol:
        q = q.filter(BrokerTrade.symbol == symbol)
    rows = q.order_by(BrokerTrade.ts.desc()).limit(2000).all()

    def _row_dict(r: BrokerTrade) -> dict:
        return {
            "id": r.id,
            "ts": r.ts.isoformat() if r.ts else None,
            "session_date": r.session_date,
            "symbol": r.symbol,
            "side": r.side,
            "size": r.size,
            "entry_price": r.entry_price,
            "stop_price": r.stop_price,
            "tp_price": r.tp_price,
            "exit_price": r.exit_price,
            "pnl_dollars": r.pnl_dollars,
            "pnl_r": r.pnl_r,
            "signal_action": r.signal_action,
            "signal_confidence": r.signal_confidence,
            "signal_zone": r.signal_zone,
            "closed_at": r.closed_at.isoformat() if r.closed_at else None,
        }

    return {"trades": [_row_dict(r) for r in rows], "count": len(rows)}


@router.get("/broker-trades/sessions")
def session_aggregates(db: Session = Depends(get_db)):
    """Per-trading-day aggregates: count, win rate, total PnL, max drawdown.

    Mirrors the table TopstepX shows on its dashboard.
    """
    from sqlalchemy import case, func

    rows = (
        db.query(
            BrokerTrade.session_date.label("date"),
            func.count().label("trades"),
            func.sum(case((BrokerTrade.pnl_dollars > 0, 1), else_=0)).label("wins"),
            func.sum(BrokerTrade.pnl_dollars).label("pnl"),
            func.max(BrokerTrade.pnl_dollars).label("biggest_win"),
            func.min(BrokerTrade.pnl_dollars).label("biggest_loss"),
            func.avg(case((BrokerTrade.pnl_dollars > 0, BrokerTrade.pnl_dollars))).label("avg_win"),
            func.avg(case((BrokerTrade.pnl_dollars <= 0, BrokerTrade.pnl_dollars))).label("avg_loss"),
        )
        .group_by(BrokerTrade.session_date)
        .order_by(BrokerTrade.session_date.desc())
        .all()
    )
    out = []
    for r in rows:
        trades = r.trades or 0
        wins = r.wins or 0
        out.append(
            {
                "date": r.date,
                "trades": trades,
                "wins": wins,
                "losses": trades - wins,
                "win_rate": round(wins / trades, 4) if trades else 0.0,
                "pnl": float(r.pnl or 0),
                "biggest_win": float(r.biggest_win or 0),
                "biggest_loss": float(r.biggest_loss or 0),
                "avg_win": float(r.avg_win or 0),
                "avg_loss": float(r.avg_loss or 0),
            }
        )
    return {"sessions": out, "count": len(out)}


# ----------------------------------------------------------------------
# Session reviews (read from /app/data/rl/sessions/<date>.json archives
# generated by session_review.py)
# ----------------------------------------------------------------------


@router.get("/sessions/review")
def list_session_reviews():
    """List archived session-review JSON files by date."""
    if not _SESSIONS_DIR.exists():
        return {"reviews": []}
    dates = sorted([p.stem for p in _SESSIONS_DIR.glob("*.json")])
    return {"reviews": dates}


@router.get("/sessions/review/{date}")
def get_session_review(date: str):
    """Return the full breakdown JSON produced by session_review.py for a date."""
    path = _SESSIONS_DIR / f"{date}.json"
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"no review archive for {date}")
    try:
        with path.open() as f:
            return json.load(f)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"corrupt archive: {e}") from None


@router.get("/sessions/review/trends/rolling")
def session_trends(window: int = 7):
    """Compare the most recent <window> days vs the previous <window>.

    Returns WR / PF / net-PnL / avg-trade for both windows so the operator
    can see whether the model is drifting session-over-session.
    """
    if not _SESSIONS_DIR.exists():
        return {"recent": None, "prior": None, "delta": None}

    archives = sorted([p for p in _SESSIONS_DIR.glob("*.json") if p.stem != "all"])
    if not archives:
        return {"recent": None, "prior": None, "delta": None}

    # Most-recent first
    archives.reverse()

    def _agg(paths: list[Path]) -> dict:
        trades = wins = 0
        net = gross_win = gross_loss = 0.0
        for p in paths:
            try:
                d = json.loads(p.read_text())
            except Exception:
                continue
            o = d.get("overview", {})
            trades += int(o.get("trades", 0))
            wins += int(o.get("wins", 0))
            net += float(o.get("net_pnl", 0))
            gross_win += float(o.get("gross_win", 0))
            gross_loss += float(o.get("gross_loss", 0))
        return {
            "days_included": len(paths),
            "trades": trades,
            "wins": wins,
            "win_rate": round(wins / trades, 4) if trades else 0.0,
            "net_pnl": round(net, 2),
            "gross_win": round(gross_win, 2),
            "gross_loss": round(gross_loss, 2),
            "profit_factor": round(gross_win / gross_loss, 3) if gross_loss else None,
            "avg_trade": round(net / trades, 2) if trades else 0.0,
        }

    recent = _agg(archives[:window])
    prior = _agg(archives[window : 2 * window])

    delta = {}
    for key in ("trades", "win_rate", "net_pnl", "profit_factor", "avg_trade"):
        rv = recent.get(key)
        pv = prior.get(key)
        if rv is None or pv is None:
            delta[key] = None
        else:
            delta[key] = round(rv - pv, 4)

    return {"recent": recent, "prior": prior, "delta": delta, "window_days": window}


# ----------------------------------------------------------------------
# Signal ↔ trade correlation (the training-feedback foundation).
# Every signal dispatched by LevelMonitor lands in stock_signals. Each closed
# round-trip lands in broker_trades. Joining them by ts + price proximity
# gives us labelled (signal_context, realized_outcome) pairs — the ground
# truth future retraining should be weighted against.
# ----------------------------------------------------------------------


@router.get("/signals")
def list_signals(
    days: int = 14,
    only_labelled: bool = False,
    db: Session = Depends(get_db),
):
    """Recent signals. Set only_labelled=true to return only ones already
    linked to a broker_trade (i.e. the trade closed and got correlated).
    """
    from datetime import timedelta as _td

    cutoff = datetime.utcnow() - _td(days=days)
    q = db.query(StockSignal).filter(StockSignal.ts >= cutoff)
    if only_labelled:
        q = q.filter(StockSignal.trade_id.isnot(None))
    rows = q.order_by(StockSignal.ts.desc()).limit(2000).all()

    def _row(s: StockSignal) -> dict:
        return {
            "id": s.id,
            "ts": s.ts.isoformat() if s.ts else None,
            "symbol": s.symbol,
            "action": s.action,
            "price": s.price,
            "confidence": s.confidence,
            "cont_p": s.cont_p,
            "rev_p": s.rev_p,
            "stop_price": s.stop_price,
            "stop_ticks": s.stop_ticks,
            "zone_center": s.zone_center,
            "zone_members": s.zone_members,
            "model_type": s.model_type,
            "trade_id": s.trade_id,
        }

    return {"signals": [_row(s) for s in rows], "count": len(rows)}


@router.post("/signals/correlate")
def correlate_signals_to_trades(
    match_window_seconds: int = 60,
    max_price_distance: float = 5.0,
    db: Session = Depends(get_db),
):
    """Join each unlinked StockSignal to the closest BrokerTrade whose entry
    was (a) within `match_window_seconds` of the signal ts, and (b) whose
    entry_price is within `max_price_distance` points of the signal price.

    Writes trade_id back onto the signal row. Idempotent: re-running only
    processes signals with trade_id IS NULL.
    """
    from datetime import timedelta as _td

    from sqlalchemy import and_

    unlinked = db.query(StockSignal).filter(StockSignal.trade_id.is_(None)).all()
    linked = 0
    ambiguous = 0
    unmatched = 0

    for sig in unlinked:
        window_lo = sig.ts - _td(seconds=match_window_seconds)
        window_hi = sig.ts + _td(seconds=match_window_seconds)

        candidates = (
            db.query(BrokerTrade)
            .filter(
                and_(
                    BrokerTrade.ts >= window_lo,
                    BrokerTrade.ts <= window_hi,
                )
            )
            .all()
        )
        # Keep only those on the matching side + within price band
        want_side = "long" if "long" in (sig.action or "").lower() else "short"
        near = [
            t for t in candidates if t.side == want_side and abs((t.entry_price or 0) - sig.price) <= max_price_distance
        ]
        if not near:
            unmatched += 1
            continue
        if len(near) > 1:
            # pick nearest by abs(ts delta)
            near.sort(key=lambda t: abs((t.ts - sig.ts).total_seconds()))
            ambiguous += 1
        sig.trade_id = near[0].id
        linked += 1

    db.commit()
    return {
        "unlinked_before": len(unlinked),
        "linked": linked,
        "ambiguous": ambiguous,  # multiple candidates — took nearest
        "unmatched": unmatched,
        "still_unlinked_after": unmatched,
        "match_window_seconds": match_window_seconds,
        "max_price_distance": max_price_distance,
    }


@router.get("/signals/labelled-dataset")
def labelled_dataset(days: int = 30, db: Session = Depends(get_db)):
    """Return joined (signal_context + realized_outcome) pairs — the format
    future RL retraining will consume as high-weight ground-truth examples.
    """
    from datetime import timedelta as _td

    cutoff = datetime.utcnow() - _td(days=days)
    rows = (
        db.query(StockSignal, BrokerTrade)
        .join(BrokerTrade, BrokerTrade.id == StockSignal.trade_id)
        .filter(StockSignal.ts >= cutoff)
        .order_by(StockSignal.ts.desc())
        .all()
    )
    out = []
    for sig, tr in rows:
        out.append(
            {
                "signal": {
                    "ts": sig.ts.isoformat() if sig.ts else None,
                    "action": sig.action,
                    "price": sig.price,
                    "confidence": sig.confidence,
                    "cont_p": sig.cont_p,
                    "rev_p": sig.rev_p,
                    "stop_ticks": sig.stop_ticks,
                    "zone_center": sig.zone_center,
                    "zone_members": sig.zone_members,
                },
                "outcome": {
                    "trade_id": tr.id,
                    "entry_price": tr.entry_price,
                    "exit_price": tr.exit_price,
                    "side": tr.side,
                    "size": tr.size,
                    "pnl_dollars": tr.pnl_dollars,
                    "pnl_r": tr.pnl_r,
                    "duration_sec": ((tr.closed_at - tr.ts).total_seconds() if tr.ts and tr.closed_at else None),
                    "closed_at": tr.closed_at.isoformat() if tr.closed_at else None,
                },
            }
        )
    return {"pairs": out, "count": len(out)}
