"""Stocks API routes — broker-trade ingestion + session-review access.

The local arnold app POSTs every closed round-trip here (entry/exit/PnL/signal
context). Without this, trade outcomes only existed in stdout + a 100-deep
in-memory dashboard deque, lost on container restart.

Session reviews are generated by backend/scripts/session_review.py (cron at
23:55 UTC) and archived to /app/data/rl/sessions/<YYYY-MM-DD>.json. The
endpoints here let the local frontend (and humans via curl) read them back.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from ...db.models import BrokerTrade, StockSignal
from ..deps import get_db

router = APIRouter(prefix="/api/stocks", tags=["stocks"])

_SESSIONS_DIR = Path("/app/data/rl/sessions")
_TRADING_PAUSED_FLAG = Path("/app/data/rl/trading_paused")


@router.get("/runtime-status")
def runtime_status(request: Request):
    """Is the autonomous server-side broker alive, what's the current
    position, and is the trading_paused kill switch active?
    """
    rt = getattr(request.app.state, "stocks_runtime", None)
    paused = _TRADING_PAUSED_FLAG.exists()

    if rt is None:
        return {
            "running": False,
            "paused": paused,
            "reason": "STOCKS_AUTONOMOUS not set or bootstrap failed at startup",
        }

    adapter = rt.adapter
    tracker = adapter.tracker
    return {
        "running": True,
        "paused": paused,
        "halted": adapter._halted,
        "halt_reason": adapter._halt_reason,
        "account_id": rt.client._account_id,
        "position": {
            "flat": tracker.is_flat,
            "side": tracker.side,
            "size": tracker.size,
            "entry_price": tracker.entry_price,
            "stop_price": tracker.stop_price,
            "peak_R": tracker.peak_R,
            "locked_half_R": tracker.locked_half_R,
        },
        "session": {
            "pnl": tracker.session_pnl,
            "trade_count": tracker.trade_count,
            "consecutive_stops": tracker.consecutive_stops,
            "trailing_dd": tracker.trailing_dd,
        },
    }


@router.post("/halt")
async def halt_trading(request: Request, flatten: bool = True):
    """Emergency stop: writes the /app/data/rl/trading_paused flag AND
    optionally liquidates any open position.

    The paused flag raises the signal-confidence floor to 0.99, muting
    every future signal until the flag is removed.
    """
    try:
        _TRADING_PAUSED_FLAG.parent.mkdir(parents=True, exist_ok=True)
        _TRADING_PAUSED_FLAG.touch()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"could not set pause flag: {e}") from None

    flattened = False
    flatten_err = None
    rt = getattr(request.app.state, "stocks_runtime", None)
    if flatten and rt is not None and not rt.adapter.tracker.is_flat:
        try:
            await rt.adapter.flatten("manual_halt")
            flattened = True
        except Exception as e:
            flatten_err = str(e)

    return {
        "paused": True,
        "flattened": flattened,
        "flatten_error": flatten_err,
        "note": "remove /app/data/rl/trading_paused to resume",
    }


@router.post("/resume")
def resume_trading():
    """Remove the trading_paused flag so new signals fire again."""
    if _TRADING_PAUSED_FLAG.exists():
        _TRADING_PAUSED_FLAG.unlink()
        return {"paused": False, "removed": True}
    return {"paused": False, "removed": False, "note": "flag was not set"}


def _parse_ts(v: str | float | None) -> datetime | None:
    if v is None:
        return None
    if isinstance(v, (int, float)):
        return datetime.fromtimestamp(v, tz=timezone.utc).replace(tzinfo=None)
    try:
        return datetime.fromisoformat(str(v).replace("Z", "+00:00")).astimezone(timezone.utc).replace(tzinfo=None)
    except Exception:
        return None


class BrokerTradeIn(BaseModel):
    """Round-trip trade payload from the local broker_adapter."""

    ts: str | float | None = None
    session_date: str
    symbol: str = "NQ"
    side: str
    size: int
    entry_price: float
    stop_price: float | None = None
    exit_price: float | None = None
    tp_price: float | None = None
    pnl_dollars: float | None = None
    pnl_r: float | None = None
    fill_latency_ms: float | None = None
    slippage_ticks: float | None = None
    was_stop: bool | None = None
    trail_count: int | None = None
    stop_ticks: float | None = None
    signal_action: str | None = None
    signal_confidence: float | None = None
    signal_zone: float | None = None
    signal_trigger: str | None = None
    signal_cont_p: float | None = None
    signal_rev_p: float | None = None
    closed_at: str | float | None = None
    # Idempotency: a deterministic key the client can supply so retries don't
    # double-insert. We store it in signal_trigger for now (string column,
    # already indexed-friendly via session_date+ts).
    client_dedupe_key: str | None = Field(default=None)


@router.post("/broker-trades")
def ingest_broker_trade(body: BrokerTradeIn, db: Session = Depends(get_db)):
    """Persist a closed round-trip from the local TopstepX adapter.

    Idempotent on (session_date, symbol, side, entry_price, closed_at) — the
    client should send the same payload on retry; we'll skip if it already
    exists.
    """
    closed_at = _parse_ts(body.closed_at)
    ts = _parse_ts(body.ts) or datetime.utcnow()

    # Cheap dedupe: same closed_at + entry_price + size + side already in DB.
    if closed_at is not None:
        existing = (
            db.query(BrokerTrade.id)
            .filter(
                BrokerTrade.closed_at == closed_at,
                BrokerTrade.symbol == body.symbol,
                BrokerTrade.side == body.side,
                BrokerTrade.entry_price == body.entry_price,
                BrokerTrade.size == body.size,
            )
            .first()
        )
        if existing:
            return {"id": existing[0], "deduped": True}

    row = BrokerTrade(
        ts=ts,
        session_date=body.session_date,
        symbol=body.symbol,
        side=body.side,
        size=body.size,
        entry_price=body.entry_price,
        stop_price=body.stop_price,
        exit_price=body.exit_price,
        pnl_dollars=body.pnl_dollars,
        pnl_r=body.pnl_r,
        fill_latency_ms=body.fill_latency_ms,
        slippage_ticks=body.slippage_ticks,
        signal_action=body.signal_action,
        signal_confidence=body.signal_confidence,
        signal_zone=body.signal_zone,
        closed_at=closed_at,
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    return {"id": row.id, "deduped": False}


@router.get("/broker-trades")
def list_broker_trades(
    days: int = 30,
    symbol: str | None = None,
    db: Session = Depends(get_db),
):
    """Return recent persisted trades — for the local dashboard's history view."""
    cutoff = datetime.utcnow() - __import__("datetime").timedelta(days=days)
    q = db.query(BrokerTrade).filter(BrokerTrade.ts >= cutoff)
    if symbol:
        q = q.filter(BrokerTrade.symbol == symbol)
    rows = q.order_by(BrokerTrade.ts.desc()).limit(2000).all()

    def _row_dict(r: BrokerTrade) -> dict:
        return {
            "id": r.id,
            "ts": r.ts.isoformat() if r.ts else None,
            "session_date": r.session_date,
            "symbol": r.symbol,
            "side": r.side,
            "size": r.size,
            "entry_price": r.entry_price,
            "stop_price": r.stop_price,
            "exit_price": r.exit_price,
            "pnl_dollars": r.pnl_dollars,
            "pnl_r": r.pnl_r,
            "signal_action": r.signal_action,
            "signal_confidence": r.signal_confidence,
            "signal_zone": r.signal_zone,
            "closed_at": r.closed_at.isoformat() if r.closed_at else None,
        }

    return {"trades": [_row_dict(r) for r in rows], "count": len(rows)}


@router.get("/broker-trades/sessions")
def session_aggregates(db: Session = Depends(get_db)):
    """Per-trading-day aggregates: count, win rate, total PnL, max drawdown.

    Mirrors the table TopstepX shows on its dashboard.
    """
    from sqlalchemy import case, func

    rows = (
        db.query(
            BrokerTrade.session_date.label("date"),
            func.count().label("trades"),
            func.sum(case((BrokerTrade.pnl_dollars > 0, 1), else_=0)).label("wins"),
            func.sum(BrokerTrade.pnl_dollars).label("pnl"),
            func.max(BrokerTrade.pnl_dollars).label("biggest_win"),
            func.min(BrokerTrade.pnl_dollars).label("biggest_loss"),
            func.avg(case((BrokerTrade.pnl_dollars > 0, BrokerTrade.pnl_dollars))).label("avg_win"),
            func.avg(case((BrokerTrade.pnl_dollars <= 0, BrokerTrade.pnl_dollars))).label("avg_loss"),
        )
        .group_by(BrokerTrade.session_date)
        .order_by(BrokerTrade.session_date.desc())
        .all()
    )
    out = []
    for r in rows:
        trades = r.trades or 0
        wins = r.wins or 0
        out.append(
            {
                "date": r.date,
                "trades": trades,
                "wins": wins,
                "losses": trades - wins,
                "win_rate": round(wins / trades, 4) if trades else 0.0,
                "pnl": float(r.pnl or 0),
                "biggest_win": float(r.biggest_win or 0),
                "biggest_loss": float(r.biggest_loss or 0),
                "avg_win": float(r.avg_win or 0),
                "avg_loss": float(r.avg_loss or 0),
            }
        )
    return {"sessions": out, "count": len(out)}


# ----------------------------------------------------------------------
# Session reviews (read from /app/data/rl/sessions/<date>.json archives
# generated by session_review.py)
# ----------------------------------------------------------------------


@router.get("/sessions/review")
def list_session_reviews():
    """List archived session-review JSON files by date."""
    if not _SESSIONS_DIR.exists():
        return {"reviews": []}
    dates = sorted([p.stem for p in _SESSIONS_DIR.glob("*.json")])
    return {"reviews": dates}


@router.get("/sessions/review/{date}")
def get_session_review(date: str):
    """Return the full breakdown JSON produced by session_review.py for a date."""
    path = _SESSIONS_DIR / f"{date}.json"
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"no review archive for {date}")
    try:
        with path.open() as f:
            return json.load(f)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"corrupt archive: {e}") from None


@router.get("/sessions/review/trends/rolling")
def session_trends(window: int = 7):
    """Compare the most recent <window> days vs the previous <window>.

    Returns WR / PF / net-PnL / avg-trade for both windows so the operator
    can see whether the model is drifting session-over-session.
    """
    if not _SESSIONS_DIR.exists():
        return {"recent": None, "prior": None, "delta": None}

    archives = sorted([p for p in _SESSIONS_DIR.glob("*.json") if p.stem != "all"])
    if not archives:
        return {"recent": None, "prior": None, "delta": None}

    # Most-recent first
    archives.reverse()

    def _agg(paths: list[Path]) -> dict:
        trades = wins = 0
        net = gross_win = gross_loss = 0.0
        for p in paths:
            try:
                d = json.loads(p.read_text())
            except Exception:
                continue
            o = d.get("overview", {})
            trades += int(o.get("trades", 0))
            wins += int(o.get("wins", 0))
            net += float(o.get("net_pnl", 0))
            gross_win += float(o.get("gross_win", 0))
            gross_loss += float(o.get("gross_loss", 0))
        return {
            "days_included": len(paths),
            "trades": trades,
            "wins": wins,
            "win_rate": round(wins / trades, 4) if trades else 0.0,
            "net_pnl": round(net, 2),
            "gross_win": round(gross_win, 2),
            "gross_loss": round(gross_loss, 2),
            "profit_factor": round(gross_win / gross_loss, 3) if gross_loss else None,
            "avg_trade": round(net / trades, 2) if trades else 0.0,
        }

    recent = _agg(archives[:window])
    prior = _agg(archives[window : 2 * window])

    delta = {}
    for key in ("trades", "win_rate", "net_pnl", "profit_factor", "avg_trade"):
        rv = recent.get(key)
        pv = prior.get(key)
        if rv is None or pv is None:
            delta[key] = None
        else:
            delta[key] = round(rv - pv, 4)

    return {"recent": recent, "prior": prior, "delta": delta, "window_days": window}


# ----------------------------------------------------------------------
# Signal ↔ trade correlation (the training-feedback foundation).
# Every signal dispatched by LevelMonitor lands in stock_signals. Each closed
# round-trip lands in broker_trades. Joining them by ts + price proximity
# gives us labelled (signal_context, realized_outcome) pairs — the ground
# truth future retraining should be weighted against.
# ----------------------------------------------------------------------


@router.get("/signals")
def list_signals(
    days: int = 14,
    only_labelled: bool = False,
    db: Session = Depends(get_db),
):
    """Recent signals. Set only_labelled=true to return only ones already
    linked to a broker_trade (i.e. the trade closed and got correlated).
    """
    from datetime import timedelta as _td

    cutoff = datetime.utcnow() - _td(days=days)
    q = db.query(StockSignal).filter(StockSignal.ts >= cutoff)
    if only_labelled:
        q = q.filter(StockSignal.trade_id.isnot(None))
    rows = q.order_by(StockSignal.ts.desc()).limit(2000).all()

    def _row(s: StockSignal) -> dict:
        return {
            "id": s.id,
            "ts": s.ts.isoformat() if s.ts else None,
            "symbol": s.symbol,
            "action": s.action,
            "price": s.price,
            "confidence": s.confidence,
            "cont_p": s.cont_p,
            "rev_p": s.rev_p,
            "stop_price": s.stop_price,
            "stop_ticks": s.stop_ticks,
            "zone_center": s.zone_center,
            "zone_members": s.zone_members,
            "model_type": s.model_type,
            "trade_id": s.trade_id,
        }

    return {"signals": [_row(s) for s in rows], "count": len(rows)}


@router.post("/signals/correlate")
def correlate_signals_to_trades(
    match_window_seconds: int = 60,
    max_price_distance: float = 5.0,
    db: Session = Depends(get_db),
):
    """Join each unlinked StockSignal to the closest BrokerTrade whose entry
    was (a) within `match_window_seconds` of the signal ts, and (b) whose
    entry_price is within `max_price_distance` points of the signal price.

    Writes trade_id back onto the signal row. Idempotent: re-running only
    processes signals with trade_id IS NULL.
    """
    from datetime import timedelta as _td

    from sqlalchemy import and_

    unlinked = db.query(StockSignal).filter(StockSignal.trade_id.is_(None)).all()
    linked = 0
    ambiguous = 0
    unmatched = 0

    for sig in unlinked:
        window_lo = sig.ts - _td(seconds=match_window_seconds)
        window_hi = sig.ts + _td(seconds=match_window_seconds)

        candidates = (
            db.query(BrokerTrade)
            .filter(
                and_(
                    BrokerTrade.ts >= window_lo,
                    BrokerTrade.ts <= window_hi,
                )
            )
            .all()
        )
        # Keep only those on the matching side + within price band
        want_side = "long" if "long" in (sig.action or "").lower() else "short"
        near = [
            t for t in candidates
            if t.side == want_side
            and abs((t.entry_price or 0) - sig.price) <= max_price_distance
        ]
        if not near:
            unmatched += 1
            continue
        if len(near) > 1:
            # pick nearest by abs(ts delta)
            near.sort(key=lambda t: abs((t.ts - sig.ts).total_seconds()))
            ambiguous += 1
        sig.trade_id = near[0].id
        linked += 1

    db.commit()
    return {
        "unlinked_before": len(unlinked),
        "linked": linked,
        "ambiguous": ambiguous,  # multiple candidates — took nearest
        "unmatched": unmatched,
        "still_unlinked_after": unmatched,
        "match_window_seconds": match_window_seconds,
        "max_price_distance": max_price_distance,
    }


@router.get("/signals/labelled-dataset")
def labelled_dataset(days: int = 30, db: Session = Depends(get_db)):
    """Return joined (signal_context + realized_outcome) pairs — the format
    future RL retraining will consume as high-weight ground-truth examples.
    """
    from datetime import timedelta as _td

    cutoff = datetime.utcnow() - _td(days=days)
    rows = (
        db.query(StockSignal, BrokerTrade)
        .join(BrokerTrade, BrokerTrade.id == StockSignal.trade_id)
        .filter(StockSignal.ts >= cutoff)
        .order_by(StockSignal.ts.desc())
        .all()
    )
    out = []
    for sig, tr in rows:
        out.append(
            {
                "signal": {
                    "ts": sig.ts.isoformat() if sig.ts else None,
                    "action": sig.action,
                    "price": sig.price,
                    "confidence": sig.confidence,
                    "cont_p": sig.cont_p,
                    "rev_p": sig.rev_p,
                    "stop_ticks": sig.stop_ticks,
                    "zone_center": sig.zone_center,
                    "zone_members": sig.zone_members,
                },
                "outcome": {
                    "trade_id": tr.id,
                    "entry_price": tr.entry_price,
                    "exit_price": tr.exit_price,
                    "side": tr.side,
                    "size": tr.size,
                    "pnl_dollars": tr.pnl_dollars,
                    "pnl_r": tr.pnl_r,
                    "duration_sec": (
                        (tr.closed_at - tr.ts).total_seconds()
                        if tr.ts and tr.closed_at
                        else None
                    ),
                    "closed_at": tr.closed_at.isoformat() if tr.closed_at else None,
                },
            }
        )
    return {"pairs": out, "count": len(out)}
