"""Extract feature vectors for M5 Setup Score model (trading setups)."""


def extract_trading_features(
    setup_type: str,
    direction: str,
    level_touched: str | None = None,
    base_score: int | None = None,
    # Orderflow
    delta: int | None = None,
    delta_pct: float | None = None,
    cvd: int | None = None,
    cvd_slope_5bar: float | None = None,
    cvd_slope_10bar: float | None = None,
    cvd_acceleration: float | None = None,
    volume: int | None = None,
    volume_ratio_vs_20bar: float | None = None,
    volume_ratio_vs_session: float | None = None,
    body_ratio_last: float | None = None,
    body_ratio_avg_3bar: float | None = None,
    spread_ticks: int | None = None,
    spread_ratio_vs_avg: float | None = None,
    passive_active_ratio: float | None = None,
    trapped_magnitude: float | None = None,
    tick_count_ratio: float | None = None,
    absorption_bar_count: int | None = None,
    delta_divergence_bars: int | None = None,
    delta_unwind_speed_bars: int | None = None,
    # Footprint
    imbalance_ratio_max: float | None = None,
    stacked_imbalance_count: int | None = None,
    stacked_imbalance_direction: str | None = None,
    big_trades_count: int | None = None,
    big_trades_net_delta: int | None = None,
    stop_run_magnitude_ticks: int | None = None,
    stop_run_volume_ratio: float | None = None,
    unfinished_auction_count_above: int | None = None,
    unfinished_auction_count_below: int | None = None,
    session_volume_total: int | None = None,
    session_volume_acceleration: float | None = None,
    # Market structure
    distance_to_level_ticks: int | None = None,
    distance_to_poc_ticks: int | None = None,
    distance_to_vwap_ticks: int | None = None,
    price_position_in_va: float | None = None,
    price_vs_vwap_sd: float | None = None,
    ib_range_ticks: int | None = None,
    ib_range_vs_avg: float | None = None,
    va_width_ticks: int | None = None,
    va_width_vs_yesterday: float | None = None,
    single_print_count_above: int | None = None,
    single_print_count_below: int | None = None,
    num_levels_within_20_ticks: int | None = None,
    # Session context
    rotation_factor: float | None = None,
    aspr: float | None = None,
    aspr_percentile: float | None = None,
    market_type: str | None = None,
    opening_type: str | None = None,
    poor_high: bool | None = None,
    poor_low: bool | None = None,
    minutes_since_rth_open: int | None = None,
    minutes_since_ib_close: int | None = None,
    # Macro
    vix_level: float | None = None,
    gex: float | None = None,
    news_event_minutes_away: int | None = None,
    news_event_importance: str | None = None,
) -> dict:
    """Extract a flat feature dict for a single M5 trading setup observation."""
    return {
        "setup_type": setup_type,
        "direction": direction,
        "level_touched": level_touched,
        "base_score": base_score,
        # Orderflow
        "delta": delta,
        "delta_pct": delta_pct,
        "cvd": cvd,
        "cvd_slope_5bar": cvd_slope_5bar,
        "cvd_slope_10bar": cvd_slope_10bar,
        "cvd_acceleration": cvd_acceleration,
        "volume": volume,
        "volume_ratio_vs_20bar": volume_ratio_vs_20bar,
        "volume_ratio_vs_session": volume_ratio_vs_session,
        "body_ratio_last": body_ratio_last,
        "body_ratio_avg_3bar": body_ratio_avg_3bar,
        "spread_ticks": spread_ticks,
        "spread_ratio_vs_avg": spread_ratio_vs_avg,
        "passive_active_ratio": passive_active_ratio,
        "trapped_magnitude": trapped_magnitude,
        "tick_count_ratio": tick_count_ratio,
        "absorption_bar_count": absorption_bar_count,
        "delta_divergence_bars": delta_divergence_bars,
        "delta_unwind_speed_bars": delta_unwind_speed_bars,
        # Footprint
        "imbalance_ratio_max": imbalance_ratio_max,
        "stacked_imbalance_count": stacked_imbalance_count,
        "stacked_imbalance_direction": stacked_imbalance_direction,
        "big_trades_count": big_trades_count,
        "big_trades_net_delta": big_trades_net_delta,
        "stop_run_magnitude_ticks": stop_run_magnitude_ticks,
        "stop_run_volume_ratio": stop_run_volume_ratio,
        "unfinished_auction_count_above": unfinished_auction_count_above,
        "unfinished_auction_count_below": unfinished_auction_count_below,
        "session_volume_total": session_volume_total,
        "session_volume_acceleration": session_volume_acceleration,
        # Market structure
        "distance_to_level_ticks": distance_to_level_ticks,
        "distance_to_poc_ticks": distance_to_poc_ticks,
        "distance_to_vwap_ticks": distance_to_vwap_ticks,
        "price_position_in_va": price_position_in_va,
        "price_vs_vwap_sd": price_vs_vwap_sd,
        "ib_range_ticks": ib_range_ticks,
        "ib_range_vs_avg": ib_range_vs_avg,
        "va_width_ticks": va_width_ticks,
        "va_width_vs_yesterday": va_width_vs_yesterday,
        "single_print_count_above": single_print_count_above,
        "single_print_count_below": single_print_count_below,
        "num_levels_within_20_ticks": num_levels_within_20_ticks,
        # Session context
        "rotation_factor": rotation_factor,
        "aspr": aspr,
        "aspr_percentile": aspr_percentile,
        "market_type": market_type,
        "opening_type": opening_type,
        "poor_high": poor_high,
        "poor_low": poor_low,
        "minutes_since_rth_open": minutes_since_rth_open,
        "minutes_since_ib_close": minutes_since_ib_close,
        # Macro
        "vix_level": vix_level,
        "gex": gex,
        "news_event_minutes_away": news_event_minutes_away,
        "news_event_importance": news_event_importance,
    }
